language: java
sudo: false
script: 
- mvn test && mvn jacoco:report coveralls:report --fail-never
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && [[ $TRAVIS_JDK_VERSION == "openjdk8" ]] &&
  { mvn deploy --settings .travis-settings.xml -DskipTests=true -B; };'
env:
  global:
    secure: fWu7zFEdkwLNOiEHG+sT6jdPqAOYijQcKK/BtTOuDdPBWHQ4ppmKC309RVuljkCx5xXwo6tNa5cA4O7EC/+WvhhRGpyMOqc2v8wxwCy1aWuuZS0pVu7UE8o2Vfu8PKg5KdvhNvvRA8qNldhnqdgqmdvwficcTOpGcEXWyfNxaBFCw7WpZEvxyybkmGhZBn+EOERTS4B7Cp/9iIT9pXTlkazAMimLCcKGbuRnJ7mcD6LV12hanjWvqaECwfYYPeeDAXFejkdpRVKogYhBybc4tqTour5qee4YzeOclOlZgHLw4gCUhMPJ/zx/odTN7jrSesoqDdLz5FfCcxxR67CwL9Eyw3B2vNhM5Hur+JHPAv/x3rWLipwjZXEqoFsNgVut9Z5nMZeCIqxdcM94ZMHREn/jaQ8AG+XGaWMqmHTSPB23yf2x7cfXCZL42RLWD/rvV7xh7zNyrAYpx1S3t0RE/KV0lCfE0oCI6Jgvylcmmo360mV6x0hezuinP+8aFPFScUeUHcN/EsQOpOfZG5MPBkagIfq7SGWvhcGrlHVrAIkZctMwxZwi5p+8bZRIXXzHPhzQc34HPXvnSMEgMKlikCNmkZ6wwH+mguwYYD0ZGtcPHej1h0sZMas4PrtknXlwtnm+J7te/zFdH78aG1YyGLfI3wZPZ1J3RKFh4aFXMek=
